### ISSUE TITLE
Реализовать компонет расчета

### ISSUE THREAD

**Issue by reznikovkg** [reznikovkg/financial-beaver#21]
Реализовать компонент расчет для иваноф банк

В дальнейшем этот компонент будет встраиваться для страницы банка. Пока что можно отобразить на любой странице.

![image](https://user-images.githubusercontent.com/36205504/235134528-dc1ca475-668f-432c-a518-350200acf322.png)

**Comment by reznikovkg** [comment]
@wolloh ваше

**Comment by wolloh** [comment]
@reznikovkg Я так понял здесь нету динамики и всё просто передается пропсами и ничего не зависит друг от друга?

**Comment by reznikovkg** [comment]
> @reznikovkg Я так понял здесь нету динамики и всё просто передается пропсами и ничего не зависит друг от друга?И про чекбоксы тоже

Добавьте минимум логики. Изменение суммы, меняет полученные доходы. Чекбоксы не учитывать.

**Comment by reznikovkg** [comment]
#29
